cd Marketplace
cmd /c "dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore --version 5.0.5"
cmd /c "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"
cmd /c "dotnet add package Microsoft.AspNetCore.Identity.UI --version 5.0.5"
cmd /c "dotnet add package Microsoft.EntityFrameworkCore.Design"
cmd /c "dotnet add package Microsoft.EntityFrameworkCore.Relational --version 5.0.5"
cmd /c "dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 5.0.5"
cmd /c "dotnet add package Microsoft.EntityFrameworkCore.Tools"
cmd /c "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design"
cmd /c "dotnet add package Pomelo.EntityFrameworkCore.MySql --version 5.0.0-alpha.2"
cmd /c "dotnet tool update --global dotnet-ef --version 5.0.5"
cmd /c "dotnet ef migrations add InitialSchema"
cmd /c "dotnet ef database update"
cmd /k "dotnet watch run"