// <auto-generated />
using System;
using Marketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marketplace.Migrations
{
    [DbContext(typeof(MarketplaceContext))]
    [Migration("20210329203935_CreateIdentityModelsLogin")]
    partial class CreateIdentityModelsLogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("AdministratorModelModuleModel", b =>
                {
                    b.Property<int>("LecturersId")
                        .HasColumnType("int");

                    b.Property<int>("ModulesId")
                        .HasColumnType("int");

                    b.HasKey("LecturersId", "ModulesId");

                    b.HasIndex("ModulesId");

                    b.ToTable("AdministratorModelModuleModel");
                });

            modelBuilder.Entity("Marketplace.Models.AdministratorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AdministratorModel");
                });

            modelBuilder.Entity("Marketplace.Models.BidModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Accepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<short>("HoursBid")
                        .HasColumnType("smallint");

                    b.Property<string>("InstructorBidded")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModuleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleModelId");

                    b.ToTable("BidModel");
                });

            modelBuilder.Entity("Marketplace.Models.InstructorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("InstructorModelListId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("ModuleModelId")
                        .HasColumnType("int");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorModelListId");

                    b.HasIndex("ModuleModelId");

                    b.ToTable("InstructorModel");
                });

            modelBuilder.Entity("Marketplace.Models.InstructorModelList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InstructorModelList");
                });

            modelBuilder.Entity("Marketplace.Models.ModuleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("AcademicYear")
                        .HasColumnType("smallint");

                    b.Property<short>("MaxHoursPerInstructor")
                        .HasColumnType("smallint");

                    b.Property<short>("MinHoursPerInstructor")
                        .HasColumnType("smallint");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("Semester")
                        .HasColumnType("smallint");

                    b.Property<int>("TotalHoursAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Marketplace.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("AdministratorModelModuleModel", b =>
                {
                    b.HasOne("Marketplace.Models.AdministratorModel", null)
                        .WithMany()
                        .HasForeignKey("LecturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Models.ModuleModel", null)
                        .WithMany()
                        .HasForeignKey("ModulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Models.BidModel", b =>
                {
                    b.HasOne("Marketplace.Models.ModuleModel", null)
                        .WithMany("Bids")
                        .HasForeignKey("ModuleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Models.InstructorModel", b =>
                {
                    b.HasOne("Marketplace.Models.InstructorModelList", null)
                        .WithMany("Instructors")
                        .HasForeignKey("InstructorModelListId");

                    b.HasOne("Marketplace.Models.ModuleModel", null)
                        .WithMany("Instructors")
                        .HasForeignKey("ModuleModelId");
                });

            modelBuilder.Entity("Marketplace.Models.InstructorModelList", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Marketplace.Models.ModuleModel", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Instructors");
                });
#pragma warning restore 612, 618
        }
    }
}
